---
title: "Special characters and variables"
author: "Lukáš Hejtmánek"
date: "20 July 2019"
output: github_document
---

Let's start with basic algebra, variable assignments adn special characters.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Variables and basic operations
Variables generally save outputs of other functions, allow you to 

```r
my_age <- 30
print(my_age)
my_age
my_age * 30
```

Variables have to start with a letter and can include underscores and numbers

```r
car1 <- "Audi"
car_2 <- "BMW"
```

Variables are case sensitive

```
number <- 5
numBer <- 10
number + numBer
```

Viewing variables without rStudio

```r
ls()
ls(pattern="num")
```

## Data Types
There is a limited number of varible types that you need to fit in, but you should be fine :)

### How to get a data type?

```r
num <- 5
char <- "hello"
class(num)
class(char)

class(c(1, 2, 3))
class(c(1:3))

```

### Numeric (float/integer)
```r
num1 <- 5
num2 <- 4
```

### Character (string)
```r
str <- "long character"
class(str)
char <- 'c' #single quotes should work as well
class(char)
class("5")
#Funnily enough, this also works in R
"char" = "h"
```

### Logical
```r
bool <- TRUE
bool2 <- 2 < 3
class(bool)
```

### Vectors
Need to contain the same data types

```r

```

### List
```r
ls <- list(number = 1, text = "Interesing")
ls$number
ls$text
class(ls)

```

### Data.Frame
```r

```

Special variables
```r
missing <- NA #usually missing value in imported data
missing_differently <- NULL # usually returned from function/undefined output

is.null(missing)
is.null(missing_differently)
```

### Converting variables

```r
num_vec1 <- 1:5
as.character(num_vec1)
as.numeric("1")
```

Task
- create a list called YEAR, which has field days=365, weeks=52
- add field to the list called minues and a field called seconds
- print days field as a "character" class

## Variable operations


### Math operations

```r
num1 <- 5
num2 <- 11
# * - + / %% ^ 
```

Questions:
1. How many hours are in a week
2. how many seconds are in a week
3. How many seconds in a year
4. how many seconds in a day

Math operations with different data types

```r
T + T
F + F
"hey" + "hey"

```

match operations across data types
```r
5 + TRUE

5 + "5"


```

## Comparing operations

```r
# == < > ! %in%

num  <- 5
num2 <- "5"
num3 <- 6

num1 == num2
num1 != num2
num1 < num2

"hello" > 0
```

And and OR selections

```r
# & |
num1 > num2
(num1 > num2) && (num2 < num1)
(num1 < num2) || (num2 == num1)

is_smoker <- T
age <- 30
# select if is smoker and above 30
# fits_group <- ____

```

## Global variables

Some variables are in the "global" scope. Scoping explanation can be found [here](https://www.datamentor.io/r-programming/environment-scope/)

```r
version
pi
```

# Naming conventions and special characters

Special characters are characters that have meaning in the R syntax. Therefore they should never be used in variable names or functions!

Just keep to letters, numbers and underscore when naming things. 

Select a style and stick with it. A possible recommended style is described [here](http://adv-r.had.co.nz/Style.html). Mainly be consistent!

## Valid R variable names

Let'S try to break R by using these symbols where they don't belong:

```r
text <- "heya"
underscore_ <- "thing"
dash- <- "thing"
text2 <- "heyhey"
texttwice <- "heyhey"
hey_3
2hey <- "heyhey"

num1/ <- 1
numDivided <- 1
num1% <- 2
I|>you <- "YES"

sum <- 10

```

